### ISSUE TITLE
Issue on vAmiga saving session

### ISSUE THREAD

**Issue by Gri-grid-07** [dirkwhoffmann/vAmiga#893]
Hi to all,
I downloaded Virtual C64, then I downloaded vAmiga and I legally bought the Kickstart ROMs on Amiga Forever.
I noticed that in vAmiga the function Machine -> Save/Save As... does not work well: the title of the vAmiga window always shows "Untitled" and not the name of the saved file.
Also I can’t restore a saved session with files .vAmiga as I do with Virtual C64 with the saved files .vc64.
Maybe I’m doing something wrong? Maybe it’s the disk (virtually) inserted in Df0?
Thank you all very much.

**Comment by dirkwhoffmann** [comment]
Since v4.0, vAmiga works differently than VirtualC64: it saves workspaces rather than snapshots when selection "Save..." from the File menu. A workspace contains all emulator settings together with all attached media. When a workspace is loaded, the emulator is reconfigured, the media files are attached, and the emulator is then restarted. As a result, the Amiga will always reboot from scratch. Exporting snapshots is still possible; there is a separate option in the File menu now. Workspaces are more stable than snapshots, as the snapshot format usually changes from release to release. 

The "Untitled" issue should be resolved in 4.1 (see #896). Please let me know, if not.

**Comment by Gri-grid-07** [comment]
Hi Dirk,

thank you very much for your kind and clear explanation!

Now I finally understand the difference between **workspaces** and **snapshots** in vAmiga. At first, I thought a "snapshot" was just a screenshot, but I now see it's a full emulator state save.

I also discovered there are **two ways** to handle snapshots in vAmiga:

1. **Take Snapshot**: which stores the snapshot internally in vAmiga. It’s very nice to be able to browse them with graphical previews.
2. **Save Snapshot**: which exports a `.vasnap` file externally (e.g., `workspace.vasnap`). This is useful for backup or sharing.

I tested both methods, and they work perfectly.  
The issue I had with "Save / Save As…" is now clear to me — it's used for saving **workspaces**, not snapshots.

Thanks again for your help and for developing such a great emulator.  
Warm greetings from Italy! 🇮🇹

Cristiano

**Comment by GINNOV** [comment]
4.1 seems to still carrying the issue. Repro steps:
1) open vamiga
2) install rom (in my case original 3.1)
3) save workspace
4) The window header is still showing Untitled 

It also appears that the problem manifests itself more frequently if you save over an existing workspace file

**Comment by dirkwhoffmann** [comment]
OK, I managed to reproduce it. Will be fixed in the next release.

**Comment by dirkwhoffmann** [comment]
Fixed in v4.2b1
